version: '3'

services:
  api:
    build:
      context: backend
      dockerfile: backend/Dockerfile
      args:
        - NODE_ENV=development
    env_file:
      - backend/.env
    networks:
      - nest_network
    ports:
      - 9000:9000
    depends_on:
      - postgres
    links:
      - postgres:postgres
    command: npm start

#  postgres:
#    image: postgres:alpine
#    restart: always
#    networks:
#      - nest_network
#    ports:
#      - 5432:5432
#    env_file:
#      - docker.env
networks:
  nest_network:
    driver: bridge